const bannedUrls = ["https://www.chutlunds.com/video/6j1k7*big+ass+cam"
    , "https://www.chutlunds.com/video/6ok2w*sm03"
    , "https://www.chutlunds.com/video/7aht0*not+pulling+out"
    , "https://www.chutlunds.com/video/7bpns*hands+on+her+knees+twerk"
    , "https://www.chutlunds.com/video/7cjgk*cb+simplegirl1996+dildo+riding"
    , "https://www.chutlunds.com/video/7cl78*cb+simplegirl1996+dildo+riding"
    , "https://www.chutlunds.com/video/7f2tv*simplegirl1996"
    , "https://www.chutlunds.com/video/7j7tr*big+booty+tease"
    , "https://www.chutlunds.com/video/7n2by*simplegirl1996"
    , "https://www.chutlunds.com/video/7q9o9*simplegirl1996+ride+a+dildo"
    , "https://www.chutlunds.com/video/7yump*simplegirl1996"
    , "https://www.chutlunds.com/video/8bjcm*slutty+teacher+jumping+on+a+huge+cock"
    , "https://www.chutlunds.com/video/8d6g7*adelina+gora"
    , "https://www.chutlunds.com/video/8d6gq*ag+anal"
    , "https://www.chutlunds.com/video/8idtf*nsnxnxbsososnsnskso"
    , "https://www.chutlunds.com/video/8irgp*simplegirl1996+23+07+21+14+14+21"
    , "https://www.chutlunds.com/video/8irgt*big+ass+riding+dildo"
    , "https://www.chutlunds.com/video/8n3dg*simplegirl+riding+dildo"
    , "https://www.chutlunds.com/video/8n26b*hot+bitch+squirting"
    , "https://www.chutlunds.com/video/8rhsv*simplegirl+dildo+machine"
    , "https://www.chutlunds.com/video/8vn34*651561561565651"
    , "https://www.chutlunds.com/video/8wxbd*fuck+machine+4"
    , "https://www.chutlunds.com/video/61g9r*simplegirl1996+2021+10+01+3"
    , "https://www.chutlunds.com/video/61iqa*simplegirl+cam"
    , "https://www.chutlunds.com/video/74h82*her+oiled+big+ass+riding+her+dildo"
    , "https://www.chutlunds.com/video/74zl8*big+oiled+ass+girl+riding+a+toy"
    , "https://www.chutlunds.com/video/77xuq*hot+oiled+ass+riding+on+a+dildo"
    , "https://www.chutlunds.com/video/78yil*wanna+fuck+her+awesome+big+bum"
    , "https://www.chutlunds.com/video/80rz7*big+bubble+butt+goddess+rides+dildo"
    , "https://www.chutlunds.com/video/82o2j*chaturbate+hot+ass+cam+simplegirl1996"
    , "https://www.chutlunds.com/video/609ve*simplegirl1996+2021+09+24+2"
    , "https://www.chutlunds.com/video/788ja*ksnwkaisndn"
    , "https://www.chutlunds.com/video/85685*ososmznzkalans"
    , "https://www.chutlunds.com/video/609ve*simplegirl1996+2021+09+24"]

    export default bannedUrls;
